name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies for NotificationService
        working-directory: ./services/NotificationService
        run: npm install

      - name: Install dependencies for HorarioService
        working-directory: ./services/HorarioService
        run: npm install

      - name: Install dependencies for ReservaService
        working-directory: ./services/ReservaService
        run: npm install

      - name: Run tests for NotificationService
        working-directory: ./services/NotificationService
        run: npm test

      - name: Run tests for HorarioService
        working-directory: ./services/HorarioService
        run: npm test

      - name: Run tests for ReservaService
        working-directory: ./services/ReservaService
        run: npm test

